/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Sun Oct  4 15:23:46 2009"
#define BUILD_TIME (1254662626L)

#define VERSION_NUMBER 0x03040300UL
#define VERSION_FEATURES 0x001e0cc6UL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x211b117eUL
#define VERSION_SANITY2 0xa481a5ccUL

#define VERSION_STRING "3.4.3"
#define VERSION_ID \
 "Unix NetHack Version 3.4.3 - last build Sun Oct  4 15:23:46 2009."

